import { Inter as Rubik } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

//Components
import Header from "@/components/Header";

const rubik = Rubik({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-rubik",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body className={cn("font-primary", rubik.variable)}>
                <Header />
                {children}
            </body>
        </html>
    );
}
